server.port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bulletinboard;
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  servlet:
    session:
      tracking-modes: cookie