drop table if exists post CASCADE;
create table post
(
    post_id bigint generated by default as identity,
    title varchar(100) not null unique,
    content longtext not null unique,
    member_id bigint not null,
    create_time datetime not null,
    view_count int not null,
    foreign key (member_id) references member(member_id) on update cascade,
    primary key (post_id)
);

drop table if exists member CASCADE;
create table member
(
    member_id bigint generated by default as identity,
    login_id varchar(30) not null unique,
    password varchar(30) not null,
    name varchar(30) not null unique,
    primary key (member_id)
);

drop table if exists comment CASCADE;
create table comment
(
    comment_id bigint generated by default as identity,
    post_id bigint not null,
    member_id bigint not null,
    content longtext not null,
    create_time datetime not null,
    foreign key (member_id) references member(member_id) on update cascade,
    foreign key (post_id) references post(post_id) on update cascade,
    primary key (comment_id)
);